services:
    mongodb:
        image: mongo:7.0
        container_name: app-mongo-db
        restart: no
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password123"
            MONGO_INITDB_DATABASE: "dzen_app"
        ports:
            - "27017:27017"
        expose:
            - "27017"
        networks:
            - primary
        volumes:
            - "./.volumes/mongodb:/data/db"

    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        container_name: app-node-api
        environment:
            - .env
            - PORT=3002
        ports:
            - "3002:3002"
        command: bash -c "npm run prisma:generate && npm run start:dev"
        networks:
            - primary
        volumes:
            - ./src:/home/node/app/src

networks:
    primary:
        driver: bridge
